server:
  port: 80  # 服务端口号

spring:
  application:
    name: cecs-gateway
  cloud:
    nacos:
      discovery:
        server-addr: nat.ckxgzxa.top:33300    # nacos通信地址
        username: rst
        password: rst
    gateway:    # 让gateway经过nacos实现自动路由转发
      discovery:
        locator:
          enabled: true # 自动根据URL规则实现路由转发
      routes: # 路由规则配置
        # 第一个路由配置, service-a路由规则
        - id: route_order_service
          #lb开头代表基于gateway的负载均衡策略选择实例
          uri: lb://order-service
          #谓词配置
      请接着设置
