server:
  port: 8007

logging:
  level:
    org.springframework.security: DEBUG
    cn.edu.cupk.cecs.watchkeeper: DEBUG

spring:
  application:
    name: cecs-watchkeeper
  datasource:
    url: jdbc:mysql://nat.ckxgzxa.top:3306/cecs?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: cecs
    password: cupk2022
  cloud:
    nacos:
      discovery:
        server-addr: nat.ckxgzxa.top:33300
        username: rst
        password: rst
  redis:
    host: nat.ckxgzxa.top
    port: 33301
    password: cupk2022
    timeout: 2000
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

