server:
  port: 8001
spring:
  application:
    name: config-server

  cloud:
    nacos:
      discovery:
        server-addr: http://nat.ckxgzxa.top:33300
      config:
        serverAddr: nat.ckxgzxa.top:33300
        prefix: PREFIX
        group: GROUP
        namespace: NAMESPACE